config/routes.rb
require 'sidekiq/web'

Yonodesperdicio::Application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  authenticated :admin_user do
    mount Sidekiq::Web, at: "/sidekiq"
  end

  root 'home#index'

  get '/noticias/(:tag)', to: 'home#noticias', as: 'noticias'
  get '/noticia/:id', to: 'home#noticia', as: 'noticia'
  post '/noticia/:id/comments', to: 'comments#create', as: 'noticia_comments', commentable_type: 'Article', article_category: 'noticia'

  get '/iniciativas_sociales/(:tag)', to: 'home#iniciativas_sociales', as: 'iniciativas_sociales'
  get '/iniciativa_social/:id', to: 'home#iniciativa', as: 'iniciativa'
  post '/iniciativa_social/:id/comments', to: 'comments#create', as: 'iniciativa_comments', commentable_type: 'Article', article_category: 'iniciativa'

  get '/ideas/(:category)', to: 'home#ideas', as: 'ideas'
  get '/ideas/de/:tag', to: 'home#ideas_tag', as: 'ideas_tag'
  get '/idea/:id', to: 'home#idea', as: 'idea'
  post '/idea/:id/comments', to: 'comments#create', as: 'idea_comments', commentable_type: 'Idea'

  get '/organizaciones', to: 'home#organizations', as: 'organizations'
  get '/organizacion/:id', to: 'home#organization', as: 'organization'

  get '/particulares', to: 'home#particulares', as: 'particulares'

  scope '/page' do
    get '/funciona', to: 'page#funciona', as: 'funciona'
    get '/faqs', to: 'page#faqs', as: 'faqs'
    get '/legal', to: 'page#legal', as: 'legal'
    get '/tos', to: 'page#tos', as: 'tos'
    get '/about', to: 'page#about', as: 'about'
    get '/privacy', to: 'page#privacy', as: 'privacy'
    get '/translate', to: 'page#translate', as: 'translate'
    get '/sitemap', to: 'page#sitemap', as: 'sitemap'
  end

  namespace :api, defaults: { format: :json } do
    get 'total_kg', to: 'base#total_kg'
    get 'categories', to: 'base#categories'
    get '', to: 'base#index'
    resources :users, :only => [:show, :create, :update, :destroy] do
      post 'rate', on: :member
    end
    resources :sessions, :only => [:create, :destroy]
    resources :ideas do
      resources :comments, :only => [:create]
    end
    resources :ads do
      resources :comments, :only => [:create]
    end
    resources :mailboxes, :only => [:show] do
      resources :conversations, :only => [:index, :show] do
        resources :messages, :only => [:index, :create]
      end
    end
    post '/new_message/(:recipient_id)', to: 'messages#new_message'
  end

  resources :ideas, path: 'mis_ideas', as: 'my_ideas'

  # FIXME: type on ads#create instead of params
  # FIXME: nolotirov2 legacy - redirect from /es/ad/create
  resources :ads, path: 'ad', path_names: { new: 'create' }

  scope '/ad' do
    #get '/create', to: redirect('/ad/create/type/1')
    get '/:id/:slug', to: 'ads#show', :as => 'adslug'
    get '/edit/id/:id', to: 'ads#edit', :as => 'ads_edit'
    get '/listall/ad_type/:type', to: 'woeid#show', as: "ads_listall"
    get '/listall/ad_type/:type/status/:status', to: 'woeid#show', as: 'ads_listall_status'
    get '/listall/page/:page/ad_type/:type', to: redirect('/ad/listall/ad_type/%{type}?page=%{page}')
    get '/listuser/id/:id', to: 'users#listads', as: 'listads_user'
  end

  # locations lists
  get '/woeid/:id/:type', to: 'woeid#show', as: 'ads_woeid'
  get '/woeid/:id/:type/page/:page', to: redirect('/woeid/%{id}/%{type}?page=%{page}')
  get '/woeid/:id/:type/status/:status', to: 'woeid#show', as: 'ads_woeid_status'
  get '/woeid/:id/:type/page/:page/status/:status', to: redirect('/woeid/%{id}/%{type}/status/%{status}?page=%{page}')

  # location change
  scope '/location' do
    get  '/change', to: 'location#ask', as: 'location_ask'
    get  '/change2', to: 'location#change', as: 'location_change'
    post '/change', to: 'location#list'
    post '/change2', to: 'location#change'
  end

  # auth
  get '/auth/login', to: redirect('/es/user/login')
  get '/user/forgot', to: redirect('/es/user/reset/new')

  devise_for :users,
    :controllers => { :registrations => 'registrations' },
    path: 'user',
    path_names: {
      sign_up: 'register',
      sign_in: 'login',
      sign_out: 'logout',
      password: 'reset'
  }

  post '/addfriend/id/:id', to: 'friendships#create', as: 'add_friend'
  post '/deletefriend/:id', to: 'friendships#destroy', as: 'destroy_friend'

  scope '/admin' do
    get '/become/:id', to: 'admin#become', as: 'become_user'
    get '/lock/:id', to: 'admin#lock', as: 'lock_user'
    get '/unlock/:id', to: 'admin#unlock', as: 'unlock_user'
  end

  get '/user/edit/id/:id', to: redirect('/user/edit'), as: 'user_edit'
  get '/profile/:username', to: 'users#profile', as: 'profile'

  # comments
  post '/ad/:id/comments', to: 'comments#create', as: 'create_comment', commentable_type: 'Ad'

  # search
  get '/search', to: 'search#search', as: 'search'

  # messaging
  resources :mailboxer_messages, controller: :messages, path: "/messages/" do
    member do
      delete 'trash'
      post 'untrash'
    end
    collection do
      delete 'trash'
    end
  end

  post 'messages/search', to: 'messages#search', as: "search_mailboxer_messages"

  # messaging legacy
  scope '/message' do
    get  '/received', to: redirect('/es/message/list'), as: 'messages_received'
    get  '/list', to: 'messages#index', as: 'messages_list'
    get  '/show/:id/subject/:subject', to: 'messages#show', as: 'message_show'
    get  '/create/id_user_to/:user_id', to: 'messages#new', as: 'message_new'
    get  '/create/id_user_to/:user_id/subject/:subject', to: "messages#new", as: 'message_new_with_subject'
    post '/create/id_user_to/:user_id', to: 'messages#create', as: 'message_create'
    post '/create/id_user_to/:user_id/subject/:subject', to: "messages#create", as: 'message_create_with_subject'
    post '/reply/:id/to/:user_id', to: 'messages#reply', as: 'message_reply'
  end

  # rss
  # nolotirov2 - legacy
  # FIX: las URLs legacy vienen asi
  # /en                     /rss/feed/woeid/766273                     /ad_type/give
  # Lo solucionamos en el nginx.conf y una configuracion para hacer el search and replace
  # http://stackoverflow.com/questions/22421522/nginx-rewrite-rule-for-replacing-space-whitespace-with-hyphen-and-convert-url-to
  scope '/rss' do
    get '/feed/woeid/:woeid/ad_type/:type', format: 'rss', to: 'rss#feed', as: 'rss_type'
    get '/feed/woeid/:woeid/ad_type/give/status/:status', format: 'rss', to: 'rss#feed', as: 'rss_status'
  end

  # contact
  get '/contact', to: 'contact#new', as: 'contacts'
  post '/contact', to: 'contact#create'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :ads
  has_many :ideas

  has_many :friendships
  has_many :friends, :through => :friendships

  before_save :default_lang
  before_create :generate_authentication_token!

  has_many :legacy_sent_messages, :class_name=> 'Legacy::Message', :foreign_key=>'user_from', :dependent=>:destroy
  has_many :legacy_recieved_messages, :class_name=> 'Legacy::Message', :foreign_key=>'user_to', :dependent=>:destroy

  validates :username,
    uniqueness: true,
    presence: true,
    length: { minimum: 3 }

  validates :name, :zipcode, presence: true

  has_attached_file :image, styles: {thumb: "100x100#", medium: "150x150#"}, :default_url => 'propias/avatar_:style.png'
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment_size :image, :in => 0.megabytes..1.megabytes

  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :lockable

  acts_as_messageable

  ratyrate_rater
  ratyrate_rateable "rating"

  def to_s
    username
  end

  def generate_authentication_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end

  def mailboxer_email(object)
    email
  end

  def unread_messages_count
    self.mailbox.inbox.unread(self).count
  end

  def admin?
    role == 1
  end

  #this method is called by devise to check for "active" state of the model
  def active_for_authentication?
    super and self.locked != 1
  end

  def unlock!
    self.update_column('locked', 0)
  end

  def lock!
    self.update_column('locked', 1)
  end

  def default_lang
    self.lang ||= "es"
  end

  def is_friend? user
    self.friends.where(id: user.id).count > 0 ? true : false
  end

  def total_quantity
    ads.give.delivered.sum(:grams)
  end

  def rating
    ratings = Rate.where(rateable: self).pluck('stars')
    (ratings.reduce(:+).to_f / ratings.size).round(1) if ratings.any?
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  before_action :authenticate_with_token!, :except => [:create]
  respond_to :json

  def show
    user = User.find(params[:id])
    if current_user && current_user.id == user.id
      render json: user, serializer: SessionUserSerializer
    else
      render json: user
    end
  end

  def create
    begin
      user = User.new(user_params)
      user.image = parse_image_data(params[:user][:image]) if params[:user][:image]

      if user.save
        render json: user, status: 201, location: [:api, user]
      else
        render json: { errors: user.errors }, status: 422
      end
    ensure
      clean_tempfile
    end
  end

  def update
    begin
      user = current_user
      user.image = parse_image_data(params[:user].delete(:image)) if params[:user][:image]

      if user.update(user_params)
        render json: user, status: 200, location: [:api, user]
      else
        render json: { errors: user.errors }, status: 422
      end
    ensure
      clean_tempfile
    end
  end

  def destroy
    current_user.destroy
    head 204
  end

  def rate
    user = User.find(params[:id])
    user.rate params[:score].to_f, current_user, "rating"
    head 201
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username, :name, :zipcode, :city, :province, :image, :accept_mailing, :fcm_registration_token)
  end

  def parse_image_data(image_data)
    filename = image_data[:filename]

    @tempfile = Tempfile.new(filename)
    @tempfile.binmode
    @tempfile.write Base64.decode64(image_data[:content])
    @tempfile.rewind

    uploaded_file = ActionDispatch::Http::UploadedFile.new(
      tempfile: @tempfile,
      filename: filename
      )

    uploaded_file.content_type = image_data[:content_type]
    uploaded_file
  end

  def clean_tempfile
    if @tempfile
      @tempfile.close
      @tempfile.unlink
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET '/ad/listuser/id/:id'
  def listads
    # ads lists for user
    @user = User.find(params[:id])
    @ads = @user.ads.page(params[:page])
  end

  # GET '/profile/:username'
  def profile
    # public profile for user
    @user = User.find_by_username(params[:username])
    if @user.nil?
      # not username, but ID
      @user = User.find(params[:username])
    end
  end

end

app/views/users/_tabnav.html.erb
<ul id="insidenav">
<!-- TODO: can an user edit or view messages from another user? -->
<!-- TODO: active class in partials -->
  <% if user_signed_in? and user.id == current_user.id %>
    <li><%= link_to_unless_current t('Volver al perfil'), profile_path(user) %></li>  
  <% end %>
</ul>

app/views/users/listads.html.erb
<% content_for :meta_title, "#{t('nlt.published_ads')} - #{@user.username}" %>

<div class="col-md-1 col-sm-1 col-xs-12">
  <%= render partial: "users/tabnav", locals: {user: current_user} %> 
</div>

<div id="inside" class="col-md-11 col-sm-11 col-xs-12">

<h1 class="title-listados"><%= t 'nlt.published_ads' %> por <%= @user.username %></h1>

<table id="listados" class="table table-responsive">
    <% if @ads.count > 0 %>
      <% @ads.each do |ad| %>
        <tr><td><%= render :partial => "ads/ad", :locals => { :ad => ad } %></td></tr>
      <% end %>
      <%= render partial: "partials/pagination", locals: { items: @ads } %>
    <% else %>
      <p><div class="info"> <%= t("nlt.no_results.on_user") %></div></p>
    <% end %>
</table>    

</div><!--/inside-->

app/views/users/profile.html.erb
<%= content_for(:meta_title, "#{t('nlt.user_profile')} - #{@user.username}") %>

<div id="profile" class="row">

  <% if user_signed_in? and @user.id == current_user.id %>
    <h1 id="title"><%= 'Hola, ' %> <%= @user.name %></h1>
  <% end %>

  <div id="profile-block" class="col-md-3 col-sm-3 col-xs-12">
    <div class="profile-header">
      <span class="col-md-8 col-sm-8 col-xs-8">Perfil</span>
      <% if user_signed_in? and @user.id == current_user.id %>
        <span class="col-md-4 col-sm-4 col-xs-4"><%= link_to 'Editar', user_edit_path(@user, :class => "btn btn-azul") %></span>
      <% end %>
    </div><!--/profile-header-->

    <div class="profile-body">
      <div class="izda col-md-4 col-sm-4 col-xs-4">
        <%= image_tag @user.image.url(:thumb), :alt => "", :class => "avatar, img-responsive" %>
      </div><!--/izda-->

      <div class="dcha col-md-8 col-sm-8 col-xs-8">
        <p class="username"><%= @user.username %></p>
        <% if user_signed_in? and @user.id != current_user.id %>
        <p>Valora a este usuario: 
          <%= rating_for @user, "rating", disable_after_rate: true, :cancel => true, cancel_place: 'right', cancel_hint: 'Cancela esta valoración!' %></p>
        <% else %>
          <%= rating_for @user, "rating" %>
          <p class="small">Tu valoración sólo se guardará si has iniciado sesión</p>
        <% end %>

      </div><!-- /dcha -->

      <div class="abajo col-md-12 col-sm-12 col-xs-12">
       <iframe width="100%" height="100" frameborder="0" style="border:0"
       src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCZtag48hMPyRv9K0xppoqTstZmJ9DHS_Q
       &q=<%= @user.zipcode %>,<%= @user.city %>&zoom=10" allowfullscreen>
       </iframe>
        <p><%= t('nlt.member_since') %>: <%= l @user.created_at, format: "%d-%m-%Y" %></p>
        <p>Código Postal: <%= @user.zipcode %></p>
        <!--<p>[Mapa]</p>-->
        <p>Comida entregada: <span id="comidaentregada"><%= grams_to_kg(@user.total_quantity) %> kg</span></p>
      </div><!-- /abajo -->
    </div><!-- /profile-body -->

  <% if user_signed_in? and @user.id == current_user.id %>
    <div class="btn btn-rojo col-md-12"><%= link_to 'Nueva idea', new_my_idea_path %></div>
    <div class="btn btn-rojo col-md-12">
      <%= link_to "Comparte alimentos", new_ad_path %>
    </div>
  <% end %>

    <div id="profile-menu">
      <% if user_signed_in? and @user.id == current_user.id %>
        <div class="btn btn-azul col-md-12">
          <% unread_messages_count = current_user.unread_messages_count %>
          <%= link_to messages_list_path, title: "#{unread_messages_count}" do %>
            Tienes <%= unread_messages_count %> mensaje(s) sin leer
          <% end %>
        </div>
        <% end %>
    </div><!-- /profile-menu -->
  </div><!-- /profile-block -->

<div class="col-md-9 col-sm-9 col-xs-12">

<p class="title-listados">Alimentos compartidos de <%= @user.username %></p>
<table id="table-alimentos" class="listados table table-responsive">
  <% if @user.ads.count > 0 %>
    <% @user.ads.each do |anuncio| %>

      <tr>
        <td><%= link_to image_tag(anuncio.image.url(:thumb), :alt => " ", :class => "img-responsive"), adslug_path(id: anuncio.id, slug: anuncio.slug) %>
          <p class="ad_status <%= anuncio.status_class %>"><%= anuncio.status_string %></p>
        </td>

        <td>
          <p class="grande enrojo"><%= link_to anuncio.title, adslug_path(id: anuncio.id, slug: anuncio.slug) %></p>
          <p class="enrojo"><%= grams_to_kg(anuncio.grams) %> kg</p>
          <p><b>Fecha límite de entrega:</b> <%= formated_date(anuncio.pick_up_date) %></p>
          <p><%= truncate_html(markdown(anuncio.body).html_safe, length: 150, omission: ' ... ') %></p>
        </td>
        <td class="botones">
          <div>
            <% if user_signed_in? and @user.id == current_user.id %>
              <p class="btn btn-azul col-md-12"><%= link_to 'Ver', adslug_path(id: anuncio.id, slug: anuncio.slug) %></p>
              <% if can? :update, anuncio %>
                <p class="btn btn-verde col-md-12"><%= link_to ads_edit_path(anuncio.id) do %>
                  Editar
              <% end %></p>

              <% if anuncio.status != 3 && can?(:destroy, anuncio) %>
                <p class="btn btn-rojo col-md-12"><%= link_to 'Eliminar', ad_path(id: anuncio.id), method: :delete, data: { confirm: '¿Seguro que quieres eliminar este alimento?' } %></p>
              <% end %>

            <% end %>
            <% end %>
          </div>
        </td>
        <% end %>
      <% else %>
        <p> <%= t("nlt.no_results.on_user") %> </p>
        </tr>
      <% end %>
  </table>

  <p class="title-listados">Ideas de <%= @user.username %></p>
  <table id="table-ideas" class="listados table table-responsive">
    <% @user.ideas.each do |idea| %>
    <tr>
      <td><%= link_to image_tag(idea.image.url(:thumb), :alt => " ", :class => "img-responsive"), idea_url(idea) %></td>
      <td>
        <p class="grande"><%= link_to idea.title, idea_url(idea) %></p>
        <p><%= truncate_html(markdown(idea.introduction).html_safe, length: 200, omission: ' ... ') %></p>
      </td>
      <td class="botones">
        <% if user_signed_in? and @user.id == current_user.id %>
          <p class="btn btn-azul col-md-12"><%= link_to 'Ver', idea_url(idea) %></p>
          <!--<p class="btn btn-azul"><%#= link_to 'Previsualizar', my_idea_path(idea) %></p>-->
          <p class="btn btn-verde col-md-12"><%= link_to 'Editar', edit_my_idea_path(idea) %></p>
          <p class="btn btn-rojo col-md-12"><%= link_to 'Eliminar', my_idea_path(idea), method: :delete, data: { confirm: 'Seguro que quieres eliminar?' } %></p>
        <% end %>
      </td>
    </tr>
    <% end %>
</table>

<hr>

<% unless current_user == @user %>
  <%= link_to message_new_path @user.id, :class => "world_link" do %>
    <%= t('nlt.send_a_message_to') %> <%= @user.username %>
    <%#= image_tag "email_send.png", :alt => "send a mesage" %>
  <% end %>
<% end %>

      <% if can? :lock, @user %>
        <li>
          <% if @user.locked? %>
            <%= link_to unlock_user_path(@user.id), data: {confirm: "¿Estas seguro que quieres desbloquear a este usuario? Podrá volver iniciar sesión."} do %>
              <%= t('nlt.admin.unlock_user') %>
              <%= image_tag "neu/24x24/actions/add.png" %>
            <% end %>
          <% else %>
            <%= link_to lock_user_path(@user.id), data: {confirm: "¿Estas seguro que quieres bloquear a este usuario? No podrá iniciar sesión."} do %>
              <%= t('nlt.admin.lock_user') %>
              <%= image_tag "neu/24x24/actions/remove.png" %>
            <% end %>
          <% end %>
        </li>
      <% end %>

      <% unless user_signed_in? and @user.id == current_user.id %>

        <% if can? :become, @user %>
          <li>
            <%= link_to t('nlt.admin.become_user'), become_user_path(@user.id) %>
          </li>
        <% end %>

      <% end %>

      <% unless @user.friends.count == 0 %>
        <div>
        <h4><%= t('nlt.friends') %>:</h4>
        <ul>
          <% @user.friends.each do |friend| %>
            <li>
              <%= link_to friend.username, profile_path(friend.username) %>
            </li>
          <% end %>
        </ul>
        <br>
        </div>
      <% end %>

  </div><!-- /ofertas-->
</div><!-- /profile -->